apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: front-envoy
  name: front-envoy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: front-envoy
    spec:
      containers:
      - image: front-envoy
        name: front-envoy
        ports:
        - containerPort: 80
        - containerPort: 8001
        resources: {}
        volumeMounts:
        - mountPath: /etc/front-envoy.yaml
          name: front-envoy-claim0
      restartPolicy: Always
      volumes:
      - name: front-envoy-claim0
        persistentVolumeClaim:
          claimName: front-envoy-claim0
status: {}
