apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: service1
  name: service1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: service1
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: "1"
        image: service1
        name: service1
        resources: {}
        volumeMounts:
        - mountPath: /etc/service-envoy.yaml
          name: service1-claim0
      restartPolicy: Always
      volumes:
      - name: service1-claim0
        persistentVolumeClaim:
          claimName: service1-claim0
status: {}
