apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: grpc-greeter-claim0
  name: grpc-greeter-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
status: {}
