apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: service2
  name: service2
spec:
  ports:
  - name: "admin"
    port: 8001
    targetPort: 8001
  selector:
    io.kompose.service: service2
status:
  loadBalancer: {}
